#!/bin/bash

echo "basic colors:"
for i in $(seq 1 16)
do
    printf %0b%s%0b "\e[48;5;${i}m" " " "\e[00m"
done
echo

echo "colors:"
for i in $(seq 0 5)
do
    for j in $(seq 0 35)
    do
	color=$((16 + (i * 36) + j))
	printf %0b%s%0b "\e[48;5;${color}m" " " "\e[00m"
    done
    echo
done

echo "grayscale:"
for i in $(seq 232 255)
do
    printf %0b%s%0b "\e[48;5;${i}m" " " "\e[00m"
done
echo